
#ifndef NETWORKINTERFACE_EXPORT_H
#define NETWORKINTERFACE_EXPORT_H

#ifdef NETWORKINTERFACE_STATIC_DEFINE
#  define NETWORKINTERFACE_EXPORT
#  define NETWORKINTERFACE_NO_EXPORT
#else
#  ifndef NETWORKINTERFACE_EXPORT
#    ifdef networkinterface_EXPORTS
        /* We are building this library */
#      define NETWORKINTERFACE_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define NETWORKINTERFACE_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef NETWORKINTERFACE_NO_EXPORT
#    define NETWORKINTERFACE_NO_EXPORT 
#  endif
#endif

#ifndef NETWORKINTERFACE_DEPRECATED
#  define NETWORKINTERFACE_DEPRECATED __declspec(deprecated)
#endif

#ifndef NETWORKINTERFACE_DEPRECATED_EXPORT
#  define NETWORKINTERFACE_DEPRECATED_EXPORT NETWORKINTERFACE_EXPORT NETWORKINTERFACE_DEPRECATED
#endif

#ifndef NETWORKINTERFACE_DEPRECATED_NO_EXPORT
#  define NETWORKINTERFACE_DEPRECATED_NO_EXPORT NETWORKINTERFACE_NO_EXPORT NETWORKINTERFACE_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef NETWORKINTERFACE_NO_DEPRECATED
#    define NETWORKINTERFACE_NO_DEPRECATED
#  endif
#endif

#endif /* NETWORKINTERFACE_EXPORT_H */
